version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
        name: Installing Dependencies
        command: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
        name: TSLint Checks
        command: yarn tslint:ci

      - run:
        name: Running tests
        command: yarn test
